import { BiodataTemplate, Collection } from "@/types";

// ─── Template Definitions ─────────────────────────────────────────────────────

export const TEMPLATES: BiodataTemplate[] = [
  // ── Royal Collection ────────────────────────────────────────────────────────
  {
    id: "royal-maharaja",
    name: "Maharaja",
    collectionId: "royal",
    tagline: "Grand & Majestic",
    colors: {
      primary: "#7B1C1C",
      secondary: "#C9A84C",
      accent: "#E8C97A",
      background: "#FFFDF5",
      text: "#1C0A0A",
      lightBg: "#FDF3DC",
    },
    fonts: { heading: "Playfair Display", body: "Lato", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["corner-ornament", "header-crown", "gold-divider", "border-scroll"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #7B1C1C 0%, #C9A84C 100%)",
  },
  {
    id: "royal-rajwadi",
    name: "Rajwadi",
    collectionId: "royal",
    tagline: "Regal Elegance",
    colors: {
      primary: "#4A0E2E",
      secondary: "#D4AF37",
      accent: "#FFD700",
      background: "#FFF9F0",
      text: "#1A0A12",
      lightBg: "#FDF0E0",
    },
    fonts: { heading: "Cormorant Garamond", body: "Raleway", decorative: "Cinzel Decorative" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["paisley-border", "mughal-arch", "gold-flourish"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #4A0E2E 0%, #D4AF37 100%)",
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    collectionId: "royal",
    tagline: "Opulent & Classic",
    colors: {
      primary: "#B8860B",
      secondary: "#8B0000",
      accent: "#FFD700",
      background: "#FFFFF0",
      text: "#2C1810",
      lightBg: "#FFFACD",
    },
    fonts: { heading: "Playfair Display", body: "Merriweather", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "rounded-square",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["gold-corner", "fleur-de-lis", "royal-seal"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #B8860B 0%, #8B0000 100%)",
  },
  {
    id: "royal-ivory",
    name: "Royal Ivory",
    collectionId: "royal",
    tagline: "Refined & Timeless",
    colors: {
      primary: "#5C3317",
      secondary: "#C4A35A",
      accent: "#E8D5A3",
      background: "#FAF7F0",
      text: "#2C1810",
      lightBg: "#F5EDD8",
    },
    fonts: { heading: "EB Garamond", body: "Lora", decorative: "Uncial Antiqua" },
    headerStyle: "split",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "card",
    decorativeElements: ["ivory-border", "lotus-divider", "heritage-seal"],
    layout: ["header", "photo", "personal", "family", "education", "career", "about", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5C3317 0%, #C4A35A 100%)",
  },

  // ── Floral Collection ───────────────────────────────────────────────────────
  {
    id: "floral-rose",
    name: "Rose Garden",
    collectionId: "floral",
    tagline: "Soft & Romantic",
    colors: {
      primary: "#C2185B",
      secondary: "#F48FB1",
      accent: "#FCE4EC",
      background: "#FFF5F7",
      text: "#3E0022",
      lightBg: "#FCE4EC",
    },
    fonts: { heading: "Dancing Script", body: "Nunito", decorative: "Great Vibes" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["rose-corner", "petal-divider", "floral-frame"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #C2185B 0%, #F48FB1 100%)",
  },
  {
    id: "floral-lotus",
    name: "Lotus Bloom",
    collectionId: "floral",
    tagline: "Sacred & Serene",
    colors: {
      primary: "#AD1457",
      secondary: "#EC407A",
      accent: "#F8BBD0",
      background: "#FFF0F5",
      text: "#37001C",
      lightBg: "#FCE4EC",
    },
    fonts: { heading: "Cormorant Garamond", body: "Open Sans", decorative: "Alex Brush" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["lotus-header", "floral-border", "petal-accent"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #AD1457 0%, #EC407A 100%)",
  },
  {
    id: "floral-jasmine",
    name: "Jasmine",
    collectionId: "floral",
    tagline: "Fresh & Delicate",
    colors: {
      primary: "#558B2F",
      secondary: "#F9A825",
      accent: "#FFF9C4",
      background: "#FAFFF5",
      text: "#1B2E0A",
      lightBg: "#F1F8E9",
    },
    fonts: { heading: "Pacifico", body: "Poppins", decorative: "Sacramento" },
    headerStyle: "left-aligned",
    photoShape: "circle",
    photoPosition: "sidebar",
    sectionStyle: "minimal",
    decorativeElements: ["jasmine-wreath", "leaf-divider", "green-accent"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #558B2F 0%, #F9A825 100%)",
  },

  // ── Traditional Hindu Collection ────────────────────────────────────────────
  {
    id: "traditional-vedic",
    name: "Vedic",
    collectionId: "traditional",
    tagline: "Sacred Traditions",
    colors: {
      primary: "#BF360C",
      secondary: "#F57F17",
      accent: "#FFECB3",
      background: "#FFFBF0",
      text: "#1A0A00",
      lightBg: "#FFF3E0",
    },
    fonts: { heading: "Tiro Devanagari Sanskrit", body: "Hind", decorative: "Yatra One" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["om-symbol", "temple-arch", "rangoli-border", "diya-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #BF360C 0%, #F57F17 100%)",
  },
  {
    id: "traditional-kashi",
    name: "Kashi Heritage",
    collectionId: "traditional",
    tagline: "Timeless & Sacred",
    colors: {
      primary: "#6A1B9A",
      secondary: "#F9A825",
      accent: "#FFF9C4",
      background: "#FDF8FF",
      text: "#1A0033",
      lightBg: "#F3E5F5",
    },
    fonts: { heading: "Uchen", body: "Mukta", decorative: "Rozha One" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "bordered",
    decorativeElements: ["temple-spire", "chakra-divider", "kashi-motif"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #6A1B9A 0%, #F9A825 100%)",
  },
  {
    id: "traditional-mangal",
    name: "Mangal",
    collectionId: "traditional",
    tagline: "Auspicious & Blessed",
    colors: {
      primary: "#C62828",
      secondary: "#EF9A9A",
      accent: "#FFCDD2",
      background: "#FFF5F5",
      text: "#1A0000",
      lightBg: "#FFEBEE",
    },
    fonts: { heading: "Baloo 2", body: "Noto Sans Devanagari", decorative: "Eczar" },
    headerStyle: "centered-ornate",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["swastika-motif", "marigold-border", "red-tilak"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #C62828 0%, #EF9A9A 100%)",
  },

  // ── Modern Minimal Collection ───────────────────────────────────────────────
  {
    id: "modern-clean",
    name: "Clean Slate",
    collectionId: "modern",
    tagline: "Professional & Crisp",
    colors: {
      primary: "#1565C0",
      secondary: "#42A5F5",
      accent: "#E3F2FD",
      background: "#FFFFFF",
      text: "#0D0D0D",
      lightBg: "#F5F9FF",
    },
    fonts: { heading: "Inter", body: "Inter", decorative: "Inter" },
    headerStyle: "left-aligned",
    photoShape: "circle",
    photoPosition: "sidebar",
    sectionStyle: "minimal",
    decorativeElements: ["thin-accent-line", "dot-separator"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)",
  },
  {
    id: "modern-executive",
    name: "Executive",
    collectionId: "modern",
    tagline: "Sophisticated Career Focus",
    colors: {
      primary: "#263238",
      secondary: "#546E7A",
      accent: "#B0BEC5",
      background: "#FAFAFA",
      text: "#101010",
      lightBg: "#ECEFF1",
    },
    fonts: { heading: "Montserrat", body: "Source Sans Pro", decorative: "Raleway" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["geometric-accent", "thin-rule"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #263238 0%, #546E7A 100%)",
  },
  {
    id: "modern-pastel",
    name: "Soft Pastel",
    collectionId: "modern",
    tagline: "Gentle & Contemporary",
    colors: {
      primary: "#5E35B1",
      secondary: "#B39DDB",
      accent: "#EDE7F6",
      background: "#FDFBFF",
      text: "#1A0050",
      lightBg: "#EDE7F6",
    },
    fonts: { heading: "Quicksand", body: "Nunito Sans", decorative: "Comfortaa" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["watercolor-splash", "soft-curve"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5E35B1 0%, #B39DDB 100%)",
  },

  // ── Luxury Gold Collection ──────────────────────────────────────────────────
  {
    id: "luxury-noir",
    name: "Noir Gold",
    collectionId: "luxury",
    tagline: "Exclusive & Premium",
    colors: {
      primary: "#111111",
      secondary: "#C9A84C",
      accent: "#FFD700",
      background: "#0A0A0A",
      text: "#F5F0E0",
      lightBg: "#1A1A1A",
    },
    fonts: { heading: "Cormorant Garamond", body: "Raleway", decorative: "Cinzel Decorative" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["gold-frame", "luxury-crest", "gold-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #111111 0%, #C9A84C 100%)",
  },
  {
    id: "luxury-champagne",
    name: "Champagne",
    collectionId: "luxury",
    tagline: "Warm & Prestigious",
    colors: {
      primary: "#8B6914",
      secondary: "#D4AF37",
      accent: "#FFF8DC",
      background: "#FFFDF5",
      text: "#1C1000",
      lightBg: "#FDF6E3",
    },
    fonts: { heading: "Bodoni Moda", body: "Libre Baskerville", decorative: "Marcellus SC" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-right",
    sectionStyle: "line-separated",
    decorativeElements: ["champagne-bubbles", "art-deco-border", "monogram"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #8B6914 0%, #D4AF37 100%)",
  },

  // ── Heritage Collection ─────────────────────────────────────────────────────
  {
    id: "heritage-vintage",
    name: "Vintage Parchment",
    collectionId: "heritage",
    tagline: "Classic & Nostalgic",
    colors: {
      primary: "#5D4037",
      secondary: "#A1887F",
      accent: "#D7CCC8",
      background: "#FDF6EE",
      text: "#1A0A00",
      lightBg: "#EFEBE9",
    },
    fonts: { heading: "IM Fell English", body: "Merriweather", decorative: "MedievalSharp" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["parchment-texture", "wax-seal", "vintage-border", "old-paper"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5D4037 0%, #A1887F 100%)",
  },
  {
    id: "heritage-temple",
    name: "Temple Gold",
    collectionId: "heritage",
    tagline: "Devotional & Proud",
    colors: {
      primary: "#4E342E",
      secondary: "#FF8F00",
      accent: "#FFE082",
      background: "#FFFBF0",
      text: "#1A0A00",
      lightBg: "#FFF8E1",
    },
    fonts: { heading: "Laila", body: "Hind Madurai", decorative: "Yatra One" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["temple-gopuram", "kalash", "deepa-motif", "sandalwood-border"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #4E342E 0%, #FF8F00 100%)",
  },
];

// ─── Collections ─────────────────────────────────────────────────────────────

export const COLLECTIONS: Collection[] = [
  {
    id: "royal",
    name: "Royal Collection",
    icon: "👑",
    tagline: "Best for traditional families",
    description: "Grand, majestic designs inspired by Mughal and Rajput heritage. Deep maroons, golds, and ornate motifs.",
    badge: "Most Popular",
    previewGradient: "linear-gradient(135deg, #7B1C1C 0%, #C9A84C 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "royal"),
  },
  {
    id: "floral",
    name: "Floral Collection",
    icon: "🌸",
    tagline: "Elegant and soft",
    description: "Beautiful floral motifs with soft pinks, roses, and jasmine-inspired designs. Perfect for a graceful impression.",
    badge: "Most Loved",
    previewGradient: "linear-gradient(135deg, #C2185B 0%, #F48FB1 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "floral"),
  },
  {
    id: "traditional",
    name: "Traditional Hindu",
    icon: "🛕",
    tagline: "Temple-inspired motifs",
    description: "Sacred symbols, Vedic patterns, and saffron-red palettes that honor Hindu traditions and values.",
    badge: "Culturally Rich",
    previewGradient: "linear-gradient(135deg, #BF360C 0%, #F57F17 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "traditional"),
  },
  {
    id: "modern",
    name: "Modern Minimal",
    icon: "✨",
    tagline: "Clean and professional",
    description: "Clean lines, professional typography, and contemporary design for the modern generation.",
    badge: "Best for Urban",
    previewGradient: "linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "modern"),
  },
  {
    id: "luxury",
    name: "Luxury Gold",
    icon: "💎",
    tagline: "Premium invitation-style designs",
    description: "Exclusive black-and-gold, champagne, and premium designs that look like high-end wedding invitations.",
    badge: "Ultra Premium",
    previewGradient: "linear-gradient(135deg, #111111 0%, #C9A84C 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "luxury"),
  },
  {
    id: "heritage",
    name: "Heritage",
    icon: "🏛",
    tagline: "Vintage and timeless",
    description: "Parchment-style, temple-inspired, and vintage designs that celebrate Indian cultural heritage.",
    badge: "Culturally Rooted",
    previewGradient: "linear-gradient(135deg, #5D4037 0%, #A1887F 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "heritage"),
  },
];

export function getCollectionById(id: string): Collection | undefined {
  return COLLECTIONS.find((c) => c.id === id);
}

export function getTemplateById(id: string): BiodataTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    features: ["Watermarked PDF", "3 basic templates", "Standard quality"],
  },
  {
    id: "premium",
    name: "Premium",
    price: 49,
    features: ["All 20 templates", "HD PDF — no watermark", "All collections", "Instant download"],
    recommended: true,
  },
  {
    id: "premium_plus",
    name: "Premium Plus",
    price: 99,
    features: [
      "Everything in Premium",
      "AI-written About Me",
      "Unlimited downloads",
      "Hindi + English bilingual",
      "WhatsApp share card",
      "Priority support",
    ],
  },
];
