import { BiodataTemplate, Collection } from "@/types";

// ─── Template Definitions ─────────────────────────────────────────────────────

export const TEMPLATES: BiodataTemplate[] = [
  // ── Royal Collection ────────────────────────────────────────────────────────
  {
    id: "royal-maharaja",
    name: "Maharaja",
    collectionId: "royal",
    tagline: "Grand & Majestic",
    colors: {
      primary: "#7B1C1C",
      secondary: "#C9A84C",
      accent: "#E8C97A",
      background: "#FFFDF5",
      text: "#1C0A0A",
      lightBg: "#FDF3DC",
    },
    fonts: { heading: "Playfair Display", body: "Lato", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["corner-ornament", "header-crown", "gold-divider", "border-scroll"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #7B1C1C 0%, #C9A84C 100%)",
  },
  {
    id: "royal-rajwadi",
    name: "Rajwadi",
    collectionId: "royal",
    tagline: "Regal Elegance",
    colors: {
      primary: "#4A0E2E",
      secondary: "#D4AF37",
      accent: "#FFD700",
      background: "#FFF9F0",
      text: "#1A0A12",
      lightBg: "#FDF0E0",
    },
    fonts: { heading: "Cormorant Garamond", body: "Raleway", decorative: "Cinzel Decorative" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["paisley-border", "mughal-arch", "gold-flourish"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #4A0E2E 0%, #D4AF37 100%)",
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    collectionId: "royal",
    tagline: "Opulent & Classic",
    colors: {
      primary: "#B8860B",
      secondary: "#8B0000",
      accent: "#FFD700",
      background: "#FFFFF0",
      text: "#2C1810",
      lightBg: "#FFFACD",
    },
    fonts: { heading: "Playfair Display", body: "Merriweather", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "rounded-square",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["gold-corner", "fleur-de-lis", "royal-seal"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #B8860B 0%, #8B0000 100%)",
  },
  {
    id: "royal-ivory",
    name: "Royal Ivory",
    collectionId: "royal",
    tagline: "Refined & Timeless",
    colors: {
      primary: "#5C3317",
      secondary: "#C4A35A",
      accent: "#E8D5A3",
      background: "#FAF7F0",
      text: "#2C1810",
      lightBg: "#F5EDD8",
    },
    fonts: { heading: "EB Garamond", body: "Lora", decorative: "Uncial Antiqua" },
    headerStyle: "split",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "card",
    decorativeElements: ["ivory-border", "lotus-divider", "heritage-seal"],
    layout: ["header", "photo", "personal", "family", "education", "career", "about", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5C3317 0%, #C4A35A 100%)",
  },
  {
    id: "royal-zardosi",
    name: "Zardosi Court",
    collectionId: "royal",
    tagline: "Embroidered & Regal",
    colors: {
      primary: "#5A1232",
      secondary: "#E0B75F",
      accent: "#F3D99A",
      background: "#FFF8F2",
      text: "#1F0B12",
      lightBg: "#F9E8D2",
    },
    fonts: { heading: "DM Serif Display", body: "Lora", decorative: "Cinzel Decorative" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "bordered",
    decorativeElements: ["zardosi-border", "peacock-divider", "royal-medallion"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5A1232 0%, #E0B75F 100%)",
  },
  {
    id: "royal-sheesh-mahal",
    name: "Sheesh Mahal",
    collectionId: "royal",
    tagline: "Gemlit & Splendid",
    colors: {
      primary: "#1F3A5F",
      secondary: "#D6C3A5",
      accent: "#B8E1DD",
      background: "#F8FBFF",
      text: "#0E1A26",
      lightBg: "#EAF2F8",
    },
    fonts: { heading: "Prata", body: "Libre Baskerville", decorative: "Forum" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["mirror-tile", "arch-window", "gem-inlay"],
    layout: ["header", "photo", "personal", "family", "education", "career", "about", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #1F3A5F 0%, #D6C3A5 100%)",
  },

  // ── Floral Collection ───────────────────────────────────────────────────────
  {
    id: "floral-rose",
    name: "Rose Garden",
    collectionId: "floral",
    tagline: "Soft & Romantic",
    colors: {
      primary: "#C2185B",
      secondary: "#F48FB1",
      accent: "#FCE4EC",
      background: "#FFF5F7",
      text: "#3E0022",
      lightBg: "#FCE4EC",
    },
    fonts: { heading: "Dancing Script", body: "Nunito", decorative: "Great Vibes" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["rose-corner", "petal-divider", "floral-frame"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #C2185B 0%, #F48FB1 100%)",
  },
  {
    id: "floral-lotus",
    name: "Lotus Bloom",
    collectionId: "floral",
    tagline: "Sacred & Serene",
    colors: {
      primary: "#AD1457",
      secondary: "#EC407A",
      accent: "#F8BBD0",
      background: "#FFF0F5",
      text: "#37001C",
      lightBg: "#FCE4EC",
    },
    fonts: { heading: "Cormorant Garamond", body: "Open Sans", decorative: "Alex Brush" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["lotus-header", "floral-border", "petal-accent"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #AD1457 0%, #EC407A 100%)",
  },
  {
    id: "floral-jasmine",
    name: "Jasmine",
    collectionId: "floral",
    tagline: "Fresh & Delicate",
    colors: {
      primary: "#558B2F",
      secondary: "#F9A825",
      accent: "#FFF9C4",
      background: "#FAFFF5",
      text: "#1B2E0A",
      lightBg: "#F1F8E9",
    },
    fonts: { heading: "Pacifico", body: "Poppins", decorative: "Sacramento" },
    headerStyle: "left-aligned",
    photoShape: "circle",
    photoPosition: "sidebar",
    sectionStyle: "minimal",
    decorativeElements: ["jasmine-wreath", "leaf-divider", "green-accent"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #558B2F 0%, #F9A825 100%)",
  },
  {
    id: "floral-peony",
    name: "Peony Whisper",
    collectionId: "floral",
    tagline: "Airy & Romantic",
    colors: {
      primary: "#9D4EDD",
      secondary: "#FF9BC2",
      accent: "#FFE5EF",
      background: "#FFF9FC",
      text: "#3F1930",
      lightBg: "#F9E0EA",
    },
    fonts: { heading: "Parisienne", body: "Mulish", decorative: "Cormorant Garamond" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["peony-cascade", "ribbon-divider", "watercolor-petal"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #9D4EDD 0%, #FF9BC2 100%)",
  },
  {
    id: "floral-gulmohar",
    name: "Gulmohar Grace",
    collectionId: "floral",
    tagline: "Vibrant & Blossoming",
    colors: {
      primary: "#D94841",
      secondary: "#FFA552",
      accent: "#FFE8D6",
      background: "#FFF8F5",
      text: "#34120F",
      lightBg: "#FBE5DC",
    },
    fonts: { heading: "Merienda", body: "Lora", decorative: "Satisfy" },
    headerStyle: "left-aligned",
    photoShape: "circle",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["gulmohar-branch", "leaf-spray", "sunset-floral"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #D94841 0%, #FFA552 100%)",
  },
  {
    id: "floral-lavender",
    name: "Lavender Vine",
    collectionId: "floral",
    tagline: "Pastel & Poetic",
    colors: {
      primary: "#6D5BD0",
      secondary: "#B8A1E3",
      accent: "#F1ECFF",
      background: "#FCFBFF",
      text: "#24194A",
      lightBg: "#ECE6FF",
    },
    fonts: { heading: "Marcellus", body: "Nunito Sans", decorative: "Allura" },
    headerStyle: "banner",
    photoShape: "rounded-square",
    photoPosition: "top-left",
    sectionStyle: "bordered",
    decorativeElements: ["lavender-stem", "vine-border", "pressed-flower"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #6D5BD0 0%, #B8A1E3 100%)",
  },

  // ── Traditional Hindu Collection ────────────────────────────────────────────
  {
    id: "traditional-vedic",
    name: "Vedic",
    collectionId: "traditional",
    tagline: "Sacred Traditions",
    colors: {
      primary: "#BF360C",
      secondary: "#F57F17",
      accent: "#FFECB3",
      background: "#FFFBF0",
      text: "#1A0A00",
      lightBg: "#FFF3E0",
    },
    fonts: { heading: "Tiro Devanagari Sanskrit", body: "Hind", decorative: "Yatra One" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["om-symbol", "temple-arch", "rangoli-border", "diya-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #BF360C 0%, #F57F17 100%)",
  },
  {
    id: "traditional-kashi",
    name: "Kashi Heritage",
    collectionId: "traditional",
    tagline: "Timeless & Sacred",
    colors: {
      primary: "#6A1B9A",
      secondary: "#F9A825",
      accent: "#FFF9C4",
      background: "#FDF8FF",
      text: "#1A0033",
      lightBg: "#F3E5F5",
    },
    fonts: { heading: "Uchen", body: "Mukta", decorative: "Rozha One" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "bordered",
    decorativeElements: ["temple-spire", "chakra-divider", "kashi-motif"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #6A1B9A 0%, #F9A825 100%)",
  },
  {
    id: "traditional-mangal",
    name: "Mangal",
    collectionId: "traditional",
    tagline: "Auspicious & Blessed",
    colors: {
      primary: "#C62828",
      secondary: "#EF9A9A",
      accent: "#FFCDD2",
      background: "#FFF5F5",
      text: "#1A0000",
      lightBg: "#FFEBEE",
    },
    fonts: { heading: "Baloo 2", body: "Noto Sans Devanagari", decorative: "Eczar" },
    headerStyle: "centered-ornate",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["swastika-motif", "marigold-border", "red-tilak"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #C62828 0%, #EF9A9A 100%)",
  },
  {
    id: "traditional-shubh-vivaah",
    name: "Shubh Vivaah",
    collectionId: "traditional",
    tagline: "Ceremonial & Bright",
    colors: {
      primary: "#E65100",
      secondary: "#2E7D6D",
      accent: "#FFE0B2",
      background: "#FFFCF6",
      text: "#2A1200",
      lightBg: "#FFF1E0",
    },
    fonts: { heading: "Rozha One", body: "Mukta", decorative: "Yatra One" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["kalash-border", "mangal-sutra-line", "shankh-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #E65100 0%, #2E7D6D 100%)",
  },
  {
    id: "traditional-tulsi-kunj",
    name: "Tulsi Kunj",
    collectionId: "traditional",
    tagline: "Earthy & Devotional",
    colors: {
      primary: "#3E6B48",
      secondary: "#C1793D",
      accent: "#F7E7C6",
      background: "#FAFBF3",
      text: "#1A261B",
      lightBg: "#EEF3E3",
    },
    fonts: { heading: "Laila", body: "Hind", decorative: "Eczar" },
    headerStyle: "split",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "line-separated",
    decorativeElements: ["tulsi-leaf", "matka-border", "sacred-thread"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #3E6B48 0%, #C1793D 100%)",
  },
  {
    id: "traditional-annapurna",
    name: "Annapurna Blessing",
    collectionId: "traditional",
    tagline: "Prosperous & Auspicious",
    colors: {
      primary: "#9C1C1C",
      secondary: "#F2B134",
      accent: "#FFE7A3",
      background: "#FFF9F1",
      text: "#240707",
      lightBg: "#FBEBD3",
    },
    fonts: { heading: "Tiro Devanagari Sanskrit", body: "Noto Sans Devanagari", decorative: "Eczar" },
    headerStyle: "centered-ornate",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["anna-kalash", "grain-motif", "auspicious-diya"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #9C1C1C 0%, #F2B134 100%)",
  },

  // ── Modern Minimal Collection ───────────────────────────────────────────────
  {
    id: "modern-clean",
    name: "Clean Slate",
    collectionId: "modern",
    tagline: "Professional & Crisp",
    colors: {
      primary: "#1565C0",
      secondary: "#42A5F5",
      accent: "#E3F2FD",
      background: "#FFFFFF",
      text: "#0D0D0D",
      lightBg: "#F5F9FF",
    },
    fonts: { heading: "Inter", body: "Inter", decorative: "Inter" },
    headerStyle: "left-aligned",
    photoShape: "circle",
    photoPosition: "sidebar",
    sectionStyle: "minimal",
    decorativeElements: ["thin-accent-line", "dot-separator"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)",
  },
  {
    id: "modern-executive",
    name: "Executive",
    collectionId: "modern",
    tagline: "Sophisticated Career Focus",
    colors: {
      primary: "#263238",
      secondary: "#546E7A",
      accent: "#B0BEC5",
      background: "#FAFAFA",
      text: "#101010",
      lightBg: "#ECEFF1",
    },
    fonts: { heading: "Montserrat", body: "Source Sans Pro", decorative: "Raleway" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["geometric-accent", "thin-rule"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #263238 0%, #546E7A 100%)",
  },
  {
    id: "modern-pastel",
    name: "Soft Pastel",
    collectionId: "modern",
    tagline: "Gentle & Contemporary",
    colors: {
      primary: "#5E35B1",
      secondary: "#B39DDB",
      accent: "#EDE7F6",
      background: "#FDFBFF",
      text: "#1A0050",
      lightBg: "#EDE7F6",
    },
    fonts: { heading: "Quicksand", body: "Nunito Sans", decorative: "Comfortaa" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["watercolor-splash", "soft-curve"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5E35B1 0%, #B39DDB 100%)",
  },
  {
    id: "modern-metro",
    name: "Metro Muse",
    collectionId: "modern",
    tagline: "Sharp & Contemporary",
    colors: {
      primary: "#0F766E",
      secondary: "#5EEAD4",
      accent: "#CCFBF1",
      background: "#F8FFFE",
      text: "#0B1F1D",
      lightBg: "#E6FFFA",
    },
    fonts: { heading: "Sora", body: "Manrope", decorative: "Space Grotesk" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "minimal",
    decorativeElements: ["signal-bars", "grid-accent", "teal-rule"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #0F766E 0%, #5EEAD4 100%)",
  },
  {
    id: "modern-nordic",
    name: "Nordic Ivory",
    collectionId: "modern",
    tagline: "Quiet & Balanced",
    colors: {
      primary: "#6B7280",
      secondary: "#D1D5DB",
      accent: "#F3F4F6",
      background: "#FFFFFF",
      text: "#111827",
      lightBg: "#F9FAFB",
    },
    fonts: { heading: "DM Sans", body: "Karla", decorative: "Syne" },
    headerStyle: "left-aligned",
    photoShape: "square",
    photoPosition: "sidebar",
    sectionStyle: "bordered",
    decorativeElements: ["soft-grid", "minimal-corner", "ash-divider"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #6B7280 0%, #D1D5DB 100%)",
  },
  {
    id: "modern-slate",
    name: "Slate Studio",
    collectionId: "modern",
    tagline: "Editorial & Sleek",
    colors: {
      primary: "#334155",
      secondary: "#94A3B8",
      accent: "#E2E8F0",
      background: "#F8FAFC",
      text: "#0F172A",
      lightBg: "#EEF2F7",
    },
    fonts: { heading: "Outfit", body: "Inter", decorative: "Archivo" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-left",
    sectionStyle: "line-separated",
    decorativeElements: ["editorial-bar", "slate-tab", "clean-divider"],
    layout: ["header", "photo", "personal", "career", "education", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #334155 0%, #94A3B8 100%)",
  },

  // ── Luxury Gold Collection ──────────────────────────────────────────────────
  {
    id: "luxury-noir",
    name: "Noir Gold",
    collectionId: "luxury",
    tagline: "Exclusive & Premium",
    colors: {
      primary: "#111111",
      secondary: "#C9A84C",
      accent: "#FFD700",
      background: "#0A0A0A",
      text: "#F5F0E0",
      lightBg: "#1A1A1A",
    },
    fonts: { heading: "Cormorant Garamond", body: "Raleway", decorative: "Cinzel Decorative" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["gold-frame", "luxury-crest", "gold-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #111111 0%, #C9A84C 100%)",
  },
  {
    id: "luxury-champagne",
    name: "Champagne",
    collectionId: "luxury",
    tagline: "Warm & Prestigious",
    colors: {
      primary: "#8B6914",
      secondary: "#D4AF37",
      accent: "#FFF8DC",
      background: "#FFFDF5",
      text: "#1C1000",
      lightBg: "#FDF6E3",
    },
    fonts: { heading: "Bodoni Moda", body: "Libre Baskerville", decorative: "Marcellus SC" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-right",
    sectionStyle: "line-separated",
    decorativeElements: ["champagne-bubbles", "art-deco-border", "monogram"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #8B6914 0%, #D4AF37 100%)",
  },
  {
    id: "luxury-velvet-crest",
    name: "Velvet Crest",
    collectionId: "luxury",
    tagline: "Dramatic & Couture",
    colors: {
      primary: "#3B0D1E",
      secondary: "#C89B3C",
      accent: "#F6E7B2",
      background: "#140A0F",
      text: "#FAF2E8",
      lightBg: "#26141B",
    },
    fonts: { heading: "Bodoni Moda", body: "Libre Baskerville", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["velvet-frame", "crest-divider", "gold-filigree"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #3B0D1E 0%, #C89B3C 100%)",
  },
  {
    id: "luxury-ivory-opal",
    name: "Ivory Opal",
    collectionId: "luxury",
    tagline: "Soft & Lavish",
    colors: {
      primary: "#8C6A56",
      secondary: "#E8D7C5",
      accent: "#FFF4EA",
      background: "#FFFCFA",
      text: "#2D1B13",
      lightBg: "#F7ECE5",
    },
    fonts: { heading: "Cormorant Garamond", body: "Manrope", decorative: "Marcellus" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["opal-sheen", "luxury-monogram", "beaded-line"],
    layout: ["header", "photo", "personal", "family", "education", "career", "about", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #8C6A56 0%, #E8D7C5 100%)",
  },
  {
    id: "luxury-emerald-reserve",
    name: "Emerald Reserve",
    collectionId: "luxury",
    tagline: "Rich & Distinguished",
    colors: {
      primary: "#0F5132",
      secondary: "#D4AF37",
      accent: "#E7D8A1",
      background: "#F6FFF9",
      text: "#081B11",
      lightBg: "#E5F4EA",
    },
    fonts: { heading: "Playfair Display", body: "Lato", decorative: "Cinzel" },
    headerStyle: "banner",
    photoShape: "square",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["emerald-cut", "reserve-seal", "gold-pinstripe"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #0F5132 0%, #D4AF37 100%)",
  },
  {
    id: "luxury-moonlit-gala",
    name: "Moonlit Gala",
    collectionId: "luxury",
    tagline: "Evening & Opulent",
    colors: {
      primary: "#1E254E",
      secondary: "#C7B8EA",
      accent: "#EFE9FF",
      background: "#F7F7FC",
      text: "#12162A",
      lightBg: "#EDEBFA",
    },
    fonts: { heading: "Prata", body: "Source Sans 3", decorative: "Alex Brush" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-left",
    sectionStyle: "card",
    decorativeElements: ["moon-crest", "silk-ribbon", "gala-border"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #1E254E 0%, #C7B8EA 100%)",
  },

  // ── Heritage Collection ─────────────────────────────────────────────────────
  {
    id: "heritage-vintage",
    name: "Vintage Parchment",
    collectionId: "heritage",
    tagline: "Classic & Nostalgic",
    colors: {
      primary: "#5D4037",
      secondary: "#A1887F",
      accent: "#D7CCC8",
      background: "#FDF6EE",
      text: "#1A0A00",
      lightBg: "#EFEBE9",
    },
    fonts: { heading: "IM Fell English", body: "Merriweather", decorative: "MedievalSharp" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["parchment-texture", "wax-seal", "vintage-border", "old-paper"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #5D4037 0%, #A1887F 100%)",
  },
  {
    id: "heritage-temple",
    name: "Temple Gold",
    collectionId: "heritage",
    tagline: "Devotional & Proud",
    colors: {
      primary: "#4E342E",
      secondary: "#FF8F00",
      accent: "#FFE082",
      background: "#FFFBF0",
      text: "#1A0A00",
      lightBg: "#FFF8E1",
    },
    fonts: { heading: "Laila", body: "Hind Madurai", decorative: "Yatra One" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["temple-gopuram", "kalash", "deepa-motif", "sandalwood-border"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #4E342E 0%, #FF8F00 100%)",
  },
  {
    id: "heritage-rajya-scroll",
    name: "Rajya Scroll",
    collectionId: "heritage",
    tagline: "Scrollwork & Stately",
    colors: {
      primary: "#704F37",
      secondary: "#C69C6D",
      accent: "#E7D1B0",
      background: "#FBF5EC",
      text: "#24150B",
      lightBg: "#F1E6D6",
    },
    fonts: { heading: "Cardo", body: "Crimson Text", decorative: "Forum" },
    headerStyle: "banner",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "bordered",
    decorativeElements: ["scroll-ends", "state-emblem", "aged-ink"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #704F37 0%, #C69C6D 100%)",
  },
  {
    id: "heritage-haveli-script",
    name: "Haveli Script",
    collectionId: "heritage",
    tagline: "Courtyard & Classic",
    colors: {
      primary: "#8D5524",
      secondary: "#D9A066",
      accent: "#F6E6CB",
      background: "#FFF8EF",
      text: "#2F1605",
      lightBg: "#F7EBD9",
    },
    fonts: { heading: "Alegreya SC", body: "Spectral", decorative: "Great Vibes" },
    headerStyle: "split",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["haveli-arch", "jaali-border", "courtyard-flourish"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #8D5524 0%, #D9A066 100%)",
  },
  {
    id: "heritage-copper-chronicle",
    name: "Copper Chronicle",
    collectionId: "heritage",
    tagline: "Antique & Storied",
    colors: {
      primary: "#7A3E2B",
      secondary: "#C77B57",
      accent: "#F5D0BC",
      background: "#FFF9F6",
      text: "#2C120A",
      lightBg: "#FBE9E0",
    },
    fonts: { heading: "Old Standard TT", body: "Libre Baskerville", decorative: "Pirata One" },
    headerStyle: "left-aligned",
    photoShape: "rounded-square",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["copperplate-edge", "ledger-line", "heritage-stamp"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #7A3E2B 0%, #C77B57 100%)",
  },

  // ── Elegant Collection ──────────────────────────────────────────────────────
  {
    id: "elegant-moonstone",
    name: "Moonstone Grace",
    collectionId: "elegant",
    tagline: "Soft & Sophisticated",
    colors: {
      primary: "#6E5F8C",
      secondary: "#C9C2E3",
      accent: "#F2EEFF",
      background: "#FFFDFF",
      text: "#241C33",
      lightBg: "#F3F0FA",
    },
    fonts: { heading: "Cormorant Garamond", body: "Mulish", decorative: "Allura" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["moonstone-border", "silk-divider", "soft-filigree"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #6E5F8C 0%, #C9C2E3 100%)",
  },
  {
    id: "elegant-blush-sonata",
    name: "Blush Sonata",
    collectionId: "elegant",
    tagline: "Rosy & Refined",
    colors: {
      primary: "#B76E79",
      secondary: "#F1C7CE",
      accent: "#FFF0F3",
      background: "#FFFDFE",
      text: "#3A1F24",
      lightBg: "#FBE7EB",
    },
    fonts: { heading: "DM Serif Display", body: "Source Sans 3", decorative: "Pinyon Script" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["sonata-line", "blush-curve", "pearl-knot"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #B76E79 0%, #F1C7CE 100%)",
  },
  {
    id: "elegant-pearl-whisper",
    name: "Pearl Whisper",
    collectionId: "elegant",
    tagline: "Airy & Understated",
    colors: {
      primary: "#8A8F9A",
      secondary: "#D8DDE6",
      accent: "#F5F7FB",
      background: "#FFFFFF",
      text: "#20242B",
      lightBg: "#F0F3F8",
    },
    fonts: { heading: "Gilda Display", body: "Manrope", decorative: "Tangerine" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-left",
    sectionStyle: "minimal",
    decorativeElements: ["pearl-dust", "gentle-rule", "airy-frame"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #8A8F9A 0%, #D8DDE6 100%)",
  },
  {
    id: "elegant-celestial-script",
    name: "Celestial Script",
    collectionId: "elegant",
    tagline: "Luminous & Graceful",
    colors: {
      primary: "#516B8C",
      secondary: "#A9C4E2",
      accent: "#E8F1FB",
      background: "#FBFDFF",
      text: "#152230",
      lightBg: "#EEF4FA",
    },
    fonts: { heading: "Prata", body: "Lora", decorative: "Parisienne" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "line-separated",
    decorativeElements: ["star-filigree", "sky-divider", "glow-crest"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #516B8C 0%, #A9C4E2 100%)",
  },
  {
    id: "elegant-ivory-reverie",
    name: "Ivory Reverie",
    collectionId: "elegant",
    tagline: "Warm & Poised",
    colors: {
      primary: "#9B8A73",
      secondary: "#E8D9C5",
      accent: "#FCF3E8",
      background: "#FFFEFB",
      text: "#2F2419",
      lightBg: "#F7F0E6",
    },
    fonts: { heading: "Marcellus", body: "Karla", decorative: "Alex Brush" },
    headerStyle: "left-aligned",
    photoShape: "square",
    photoPosition: "sidebar",
    sectionStyle: "card",
    decorativeElements: ["ivory-scroll", "soft-corner", "linen-accent"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #9B8A73 0%, #E8D9C5 100%)",
  },
  {
    id: "elegant-lilac-heirloom",
    name: "Lilac Heirloom",
    collectionId: "elegant",
    tagline: "Vintage & Delicate",
    colors: {
      primary: "#8A5FA8",
      secondary: "#D9C4EA",
      accent: "#F5EEFB",
      background: "#FFFCFF",
      text: "#291A33",
      lightBg: "#F2EAF8",
    },
    fonts: { heading: "Bellefair", body: "Nunito Sans", decorative: "Qwigley" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "bordered",
    decorativeElements: ["lilac-vine", "heirloom-badge", "lace-divider"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #8A5FA8 0%, #D9C4EA 100%)",
  },
  {
    id: "elegant-misty-calligraphy",
    name: "Misty Calligraphy",
    collectionId: "elegant",
    tagline: "Cool & Contemporary",
    colors: {
      primary: "#5F7C8A",
      secondary: "#C6D7DF",
      accent: "#EDF5F7",
      background: "#FCFEFF",
      text: "#1D2B30",
      lightBg: "#EAF1F4",
    },
    fonts: { heading: "Cormorant Garamond", body: "Figtree", decorative: "Great Vibes" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-left",
    sectionStyle: "minimal",
    decorativeElements: ["mist-border", "ink-swoosh", "calligraphy-loop"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #5F7C8A 0%, #C6D7DF 100%)",
  },

  // ── Regional Collection ─────────────────────────────────────────────────────
  {
    id: "regional-kanchipuram",
    name: "Kanchipuram Classic",
    collectionId: "regional",
    tagline: "Silken & South Indian",
    colors: {
      primary: "#7A1F3D",
      secondary: "#C9A227",
      accent: "#F6DF9A",
      background: "#FFF9F2",
      text: "#290A14",
      lightBg: "#FBEBD6",
    },
    fonts: { heading: "Laila", body: "Hind Madurai", decorative: "Cinzel" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["temple-border", "silk-weave", "south-lotus"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #7A1F3D 0%, #C9A227 100%)",
  },
  {
    id: "regional-garba-glow",
    name: "Garba Glow",
    collectionId: "regional",
    tagline: "Festive & Gujarati",
    colors: {
      primary: "#C2410C",
      secondary: "#1D4ED8",
      accent: "#FFE7B8",
      background: "#FFF9F3",
      text: "#2A1105",
      lightBg: "#FBE9D2",
    },
    fonts: { heading: "Baloo 2", body: "Mukta", decorative: "Yatra One" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-right",
    sectionStyle: "card",
    decorativeElements: ["garba-wheel", "mirror-work", "bandhani-dot"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #C2410C 0%, #1D4ED8 100%)",
  },
  {
    id: "regional-shonar-bangla",
    name: "Shonar Bangla",
    collectionId: "regional",
    tagline: "Warm & Bengali",
    colors: {
      primary: "#B45309",
      secondary: "#B91C1C",
      accent: "#FDE68A",
      background: "#FFFBF4",
      text: "#2A1405",
      lightBg: "#F9EDD3",
    },
    fonts: { heading: "Noto Serif Bengali", body: "Hind Siliguri", decorative: "Eczar" },
    headerStyle: "left-aligned",
    photoShape: "rounded-square",
    photoPosition: "sidebar",
    sectionStyle: "line-separated",
    decorativeElements: ["alpana-border", "shola-flower", "bengal-lamp"],
    layout: ["header", "photo", "personal", "about", "education", "career", "family", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #B45309 0%, #B91C1C 100%)",
  },
  {
    id: "regional-peshwa-pride",
    name: "Peshwa Pride",
    collectionId: "regional",
    tagline: "Maratha & Majestic",
    colors: {
      primary: "#7C2D12",
      secondary: "#D97706",
      accent: "#FED7AA",
      background: "#FFF8F2",
      text: "#2B1207",
      lightBg: "#FBE8DA",
    },
    fonts: { heading: "Rozha One", body: "Mukta", decorative: "Marcellus SC" },
    headerStyle: "centered-ornate",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "card",
    decorativeElements: ["peshwa-turban", "fort-divider", "saffron-seal"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #7C2D12 0%, #D97706 100%)",
  },
  {
    id: "regional-desert-jharokha",
    name: "Desert Jharokha",
    collectionId: "regional",
    tagline: "Rajasthani & Sunlit",
    colors: {
      primary: "#A16207",
      secondary: "#B45309",
      accent: "#FDE7C3",
      background: "#FFFAF2",
      text: "#2B1905",
      lightBg: "#F9EAD0",
    },
    fonts: { heading: "Prata", body: "Poppins", decorative: "Cinzel Decorative" },
    headerStyle: "banner",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["jharokha-arch", "desert-flower", "camel-bell-line"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #A16207 0%, #B45309 100%)",
  },
  {
    id: "regional-malabar-coast",
    name: "Malabar Coast",
    collectionId: "regional",
    tagline: "Coastal & Serene",
    colors: {
      primary: "#0F766E",
      secondary: "#F59E0B",
      accent: "#D1FAE5",
      background: "#F7FFFC",
      text: "#08201C",
      lightBg: "#E7F6F1",
    },
    fonts: { heading: "Playfair Display", body: "Manrope", decorative: "Sail" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "top-right",
    sectionStyle: "minimal",
    decorativeElements: ["coconut-frond", "boat-line", "coastal-wave"],
    layout: ["header", "photo", "personal", "education", "career", "about", "family", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #0F766E 0%, #F59E0B 100%)",
  },
  {
    id: "regional-deccan-durbar",
    name: "Deccan Durbar",
    collectionId: "regional",
    tagline: "Jewel-toned & Regal",
    colors: {
      primary: "#5B21B6",
      secondary: "#EC4899",
      accent: "#F3E8FF",
      background: "#FDF8FF",
      text: "#230F42",
      lightBg: "#F5ECFB",
    },
    fonts: { heading: "Forum", body: "Nunito Sans", decorative: "Yeseva One" },
    headerStyle: "centered-ornate",
    photoShape: "square",
    photoPosition: "sidebar",
    sectionStyle: "card",
    decorativeElements: ["bidri-pattern", "deccan-arch", "jewel-divider"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "landscape",
    previewColor: "linear-gradient(135deg, #5B21B6 0%, #EC4899 100%)",
  },
  {
    id: "regional-assam-silk",
    name: "Assam Silk",
    collectionId: "regional",
    tagline: "Golden & Graceful",
    colors: {
      primary: "#3F6212",
      secondary: "#EAB308",
      accent: "#FEF3C7",
      background: "#FDFFF8",
      text: "#1B2607",
      lightBg: "#F4F6D8",
    },
    fonts: { heading: "Cormorant Garamond", body: "Lora", decorative: "Sura" },
    headerStyle: "left-aligned",
    photoShape: "oval",
    photoPosition: "top-left",
    sectionStyle: "line-separated",
    decorativeElements: ["mekhela-stripe", "silk-thread", "rhino-seal"],
    layout: ["header", "photo", "personal", "family", "about", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #3F6212 0%, #EAB308 100%)",
  },
  {
    id: "premium-royal-gold",
    name: "Royal Gold",
    collectionId: "premium",
    isPremium: true,
    tagline: "Midnight Navy with Gold Accents",
    colors: {
      primary: "#c9a84c",
      secondary: "#1a1a3e",
      accent: "#c9a84c",
      background: "#1a1a3e",
      text: "#f5e6c4",
      lightBg: "#2a2a5e",
    },
    fonts: { heading: "Cinzel", body: "Cormorant Garamond", decorative: "Playfair Display" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "bordered",
    decorativeElements: ["gold-corner-frame", "diamond-divider", "ornate-border", "gold-seal"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #1a1a3e 0%, #c9a84c 100%)",
  },
  {
    id: "premium-blush-bloom",
    name: "Blush Bloom",
    collectionId: "premium",
    isPremium: true,
    tagline: "Romantic Rose with Floral Elegance",
    colors: {
      primary: "#6b1a2e",
      secondary: "#c0607c",
      accent: "#f7c5d0",
      background: "#fff8f6",
      text: "#3d1018",
      lightBg: "#ffe8ec",
    },
    fonts: { heading: "Playfair Display", body: "Raleway", decorative: "Cormorant Garamond" },
    headerStyle: "centered-ornate",
    photoShape: "circle",
    photoPosition: "top-center",
    sectionStyle: "card",
    decorativeElements: ["rose-petal-border", "bloom-divider", "cursive-accent", "petal-corner"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #6b1a2e 0%, #f7c5d0 100%)",
  },
  {
    id: "premium-emerald-luxe",
    name: "Emerald Luxe",
    collectionId: "premium",
    isPremium: true,
    tagline: "Forest Green with Gold Geometry",
    colors: {
      primary: "#1a3a2e",
      secondary: "#c8a96e",
      accent: "#c8a96e",
      background: "#f5f0e8",
      text: "#1a2e20",
      lightBg: "#e8f0e8",
    },
    fonts: { heading: "Playfair Display", body: "Raleway", decorative: "Cinzel" },
    headerStyle: "split",
    photoShape: "rounded-square",
    photoPosition: "sidebar",
    sectionStyle: "bordered",
    decorativeElements: ["geometric-pattern", "diamond-accent", "emerald-border", "gold-line"],
    layout: ["header", "photo", "personal", "about", "family", "education", "career", "expectations", "contact"],
    orientation: "portrait",
    previewColor: "linear-gradient(135deg, #1a3a2e 0%, #c8a96e 100%)",
  },
];

// ─── Collections ─────────────────────────────────────────────────────────────

export const COLLECTIONS: Collection[] = [
  {
    id: "royal",
    name: "Royal Collection",
    icon: "👑",
    tagline: "Best for traditional families",
    description: "Grand, majestic designs inspired by Mughal and Rajput heritage. Deep maroons, golds, and ornate motifs.",
    badge: "Most Popular",
    previewGradient: "linear-gradient(135deg, #7B1C1C 0%, #C9A84C 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "royal"),
  },
  {
    id: "floral",
    name: "Floral Collection",
    icon: "🌸",
    tagline: "Elegant and soft",
    description: "Beautiful floral motifs with soft pinks, roses, and jasmine-inspired designs. Perfect for a graceful impression.",
    badge: "Most Loved",
    previewGradient: "linear-gradient(135deg, #C2185B 0%, #F48FB1 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "floral"),
  },
  {
    id: "traditional",
    name: "Traditional Hindu",
    icon: "🛕",
    tagline: "Temple-inspired motifs",
    description: "Sacred symbols, Vedic patterns, and saffron-red palettes that honor Hindu traditions and values.",
    badge: "Culturally Rich",
    previewGradient: "linear-gradient(135deg, #BF360C 0%, #F57F17 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "traditional"),
  },
  {
    id: "modern",
    name: "Modern Minimal",
    icon: "✨",
    tagline: "Clean and professional",
    description: "Clean lines, professional typography, and contemporary design for the modern generation.",
    badge: "Best for Urban",
    previewGradient: "linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "modern"),
  },
  {
    id: "luxury",
    name: "Luxury Gold",
    icon: "💎",
    tagline: "Premium invitation-style designs",
    description: "Exclusive black-and-gold, champagne, and premium designs that look like high-end wedding invitations.",
    badge: "Ultra Premium",
    previewGradient: "linear-gradient(135deg, #111111 0%, #C9A84C 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "luxury"),
  },
  {
    id: "premium",
    name: "Premium Exclusive",
    icon: "💎",
    tagline: "Ultra-premium designer templates",
    description:
      "Handcrafted exclusive designs with rich colors, elegant typography, and premium finishes. Available only with the ₹49 HD download.",
    badge: "Premium Only",
    previewGradient: "linear-gradient(135deg, #1a1a3e 0%, #c9a84c 50%, #1a3a2e 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "premium"),
  },
  {
    id: "heritage",
    name: "Heritage",
    icon: "🏛",
    tagline: "Vintage and timeless",
    description: "Parchment-style, temple-inspired, and vintage designs that celebrate Indian cultural heritage.",
    badge: "Culturally Rooted",
    previewGradient: "linear-gradient(135deg, #5D4037 0%, #A1887F 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "heritage"),
  },
  {
    id: "elegant",
    name: "Elegant & Graceful",
    icon: "🕊️",
    tagline: "Sophisticated and graceful",
    description: "Sophisticated designs with soft tones, calligraphy fonts, and understated luxury for a polished first impression.",
    badge: "New Collection",
    previewGradient: "linear-gradient(135deg, #6E5F8C 0%, #C9C2E3 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "elegant"),
  },
  {
    id: "regional",
    name: "Regional Pride",
    icon: "🎨",
    tagline: "Celebrate regional culture",
    description: "Designs inspired by South Indian, Gujarati, Bengali, Marathi, Rajasthani, and other Indian regional aesthetics.",
    badge: "Cultural Pride",
    previewGradient: "linear-gradient(135deg, #7A1F3D 0%, #C9A227 100%)",
    templates: TEMPLATES.filter((t) => t.collectionId === "regional"),
  },
];

export function getCollectionById(id: string): Collection | undefined {
  return COLLECTIONS.find((c) => c.id === id);
}

export function getTemplateById(id: string): BiodataTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    features: ["Watermarked PDF", "3 basic templates", "Standard quality"],
  },
  {
    id: "premium",
    name: "Premium",
    price: 49,
    features: ["All 50 templates", "HD PDF — no watermark", "All collections", "Instant download"],
    recommended: true,
  },
  {
    id: "premium_plus",
    name: "Premium Plus",
    price: 99,
    features: [
      "Everything in Premium",
      "AI-written About Me",
      "Unlimited downloads",
      "Hindi + English bilingual",
      "WhatsApp share card",
      "Priority support",
    ],
  },
];
